**Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.**

**HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.**

In [139]:
import numpy as np
def alexmatrix(lst,increasing=True,N=None):
    if N==None:
        N=len(lst)
    if increasing==False:
        mat1=[]
        for i in range(N):
            mat1.append([j**(N-i-1) for j in lst])
        return np.asarray(mat1).T
    elif increasing==True:
        mat1=[]
        for i in range(N):
            mat1.append([j**i for j in lst])
        return np.asarray(mat1).T

In [140]:
alexmatrix([1,2,3],increasing=False,N=5)


array([[ 1,  1,  1,  1,  1],
       [16,  8,  4,  2,  1],
       [81, 27,  9,  3,  1]])

In [141]:
alexmatrix([1,2,3],increasing=True,N=5)

array([[ 1,  1,  1,  1,  1],
       [ 1,  2,  4,  8, 16],
       [ 1,  3,  9, 27, 81]])

In [142]:
alexmatrix([1,2,3,6,7,8],increasing=False)

array([[    1,     1,     1,     1,     1,     1],
       [   32,    16,     8,     4,     2,     1],
       [  243,    81,    27,     9,     3,     1],
       [ 7776,  1296,   216,    36,     6,     1],
       [16807,  2401,   343,    49,     7,     1],
       [32768,  4096,   512,    64,     8,     1]])

**Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [143]:
def moving_avg(lst,k):
    #lst=np.asarray(lst)
    if k>0:
        m_avg=[]
        for i in range(len(lst)-k+1):
            avg=sum(lst[i:i+k])/k
            m_avg.append(round(avg,1))
        print("Moving average for a window of {} is {}".format(k,m_avg))
    else:
        print('Value of the window should be greater than 0 ')

In [144]:
lst=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
moving_avg(lst,k)

Moving average for a window of 3 is [5.0, 4.7, 5.7, 6.7, 9.7, 28.7, 49.3, 72.7, 84.0, 93.3, 116.3]
